### PR TITLE
Use bun instead of node

### PR DESCRIPTION
**Pull request by nojaf**
Jumping on the hype train but I was surprised how easy this was to swap out.
Everything is definitely faster, although this won't overly change the local experience much.
There is a part of me just happy to ditch node.

### CODE REVIEW

**Comment by nojaf** [comment]
On main:
```
STAGE #0 yarn install finished. 6146ms.
bundle frontend/step-2> ✓ built in 5.60s
bundle frontend/step-2> Done in 23.28s
STAGE #6 bundle frontend finished. 23710ms.
```

This PR:
```
STAGE #0 bun install finished. 567ms
bundle frontend/step-2> ✓ built in 5.00s
bundle frontend/step-2> finished. 24056ms.
STAGE #6 bundle frontend finished. 24383ms.
```

**Comment by nojaf** [comment]
Also from the bun docs:
image

https://bun.sh/guides/ecosystem/vite

Things will still improve over time.

**Review by dawedawe — APPROVED** [review]

**Comment by nojaf** [comment]
@josh-degraw I'm not sure where we talked about Bun not working on Windows but with `v1.0.26-canary.53 (862d35d8)` I was able to run things in Windows.

```
# WARNING: No stability is guaranteed on the experimental Windows builds
powershell -c "irm bun.sh/install.ps1|iex"
```

**Comment by josh-degraw** [comment]
If it worked for you I say go for it  🚀

**Pull request merged**
